/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_sprite/msg/KeyframePlayerGoal.msg */
#ifndef CORDIAL_SPRITE_MESSAGE_KEYFRAMEPLAYERGOAL_H
#define CORDIAL_SPRITE_MESSAGE_KEYFRAMEPLAYERGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cordial_sprite
{
template <class ContainerAllocator>
struct KeyframePlayerGoal_ {
  typedef KeyframePlayerGoal_<ContainerAllocator> Type;

  KeyframePlayerGoal_()
  : behavior()
  , args()
  {
  }

  KeyframePlayerGoal_(const ContainerAllocator& _alloc)
  : behavior(_alloc)
  , args(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _behavior_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  behavior;

  typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _args_type;
  std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  args;


  typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct KeyframePlayerGoal
typedef  ::cordial_sprite::KeyframePlayerGoal_<std::allocator<void> > KeyframePlayerGoal;

typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerGoal> KeyframePlayerGoalPtr;
typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerGoal const> KeyframePlayerGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_sprite

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a45daf5330f8aa20ddeb4a78b462fd7";
  }

  static const char* value(const  ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4a45daf5330f8aa2ULL;
  static const uint64_t static_value2 = 0x0ddeb4a78b462fd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_sprite/KeyframePlayerGoal";
  }

  static const char* value(const  ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string behavior\n\
string[] args\n\
\n\
";
  }

  static const char* value(const  ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.behavior);
    stream.next(m.args);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct KeyframePlayerGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> & v) 
  {
    s << indent << "behavior: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.behavior);
    s << indent << "args[]" << std::endl;
    for (size_t i = 0; i < v.args.size(); ++i)
    {
      s << indent << "  args[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.args[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_SPRITE_MESSAGE_KEYFRAMEPLAYERGOAL_H

