/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_sprite/msg/KeyframePlayerActionGoal.msg */
#ifndef CORDIAL_SPRITE_MESSAGE_KEYFRAMEPLAYERACTIONGOAL_H
#define CORDIAL_SPRITE_MESSAGE_KEYFRAMEPLAYERACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "cordial_sprite/KeyframePlayerGoal.h"

namespace cordial_sprite
{
template <class ContainerAllocator>
struct KeyframePlayerActionGoal_ {
  typedef KeyframePlayerActionGoal_<ContainerAllocator> Type;

  KeyframePlayerActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  KeyframePlayerActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator>  _goal_type;
   ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct KeyframePlayerActionGoal
typedef  ::cordial_sprite::KeyframePlayerActionGoal_<std::allocator<void> > KeyframePlayerActionGoal;

typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerActionGoal> KeyframePlayerActionGoalPtr;
typedef boost::shared_ptr< ::cordial_sprite::KeyframePlayerActionGoal const> KeyframePlayerActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_sprite

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a440f48ebd54cf53b44b336f2315e19e";
  }

  static const char* value(const  ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa440f48ebd54cf53ULL;
  static const uint64_t static_value2 = 0xb44b336f2315e19eULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_sprite/KeyframePlayerActionGoal";
  }

  static const char* value(const  ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
KeyframePlayerGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: cordial_sprite/KeyframePlayerGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string behavior\n\
string[] args\n\
\n\
";
  }

  static const char* value(const  ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct KeyframePlayerActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_sprite::KeyframePlayerActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::cordial_sprite::KeyframePlayerGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_SPRITE_MESSAGE_KEYFRAMEPLAYERACTIONGOAL_H

