/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_face/msg/Keyframe.msg */
#ifndef CORDIAL_FACE_MESSAGE_KEYFRAME_H
#define CORDIAL_FACE_MESSAGE_KEYFRAME_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cordial_face
{
template <class ContainerAllocator>
struct Keyframe_ {
  typedef Keyframe_<ContainerAllocator> Type;

  Keyframe_()
  : positions()
  {
  }

  Keyframe_(const ContainerAllocator& _alloc)
  : positions(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _positions_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  positions;


  typedef boost::shared_ptr< ::cordial_face::Keyframe_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_face::Keyframe_<ContainerAllocator>  const> ConstPtr;
}; // struct Keyframe
typedef  ::cordial_face::Keyframe_<std::allocator<void> > Keyframe;

typedef boost::shared_ptr< ::cordial_face::Keyframe> KeyframePtr;
typedef boost::shared_ptr< ::cordial_face::Keyframe const> KeyframeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_face::Keyframe_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_face::Keyframe_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_face

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_face::Keyframe_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_face::Keyframe_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_face::Keyframe_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3b33cf2d1f9005e741ee291d519b97ee";
  }

  static const char* value(const  ::cordial_face::Keyframe_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3b33cf2d1f9005e7ULL;
  static const uint64_t static_value2 = 0x41ee291d519b97eeULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_face::Keyframe_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_face/Keyframe";
  }

  static const char* value(const  ::cordial_face::Keyframe_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_face::Keyframe_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] positions\n\
";
  }

  static const char* value(const  ::cordial_face::Keyframe_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_face::Keyframe_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.positions);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Keyframe_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_face::Keyframe_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_face::Keyframe_<ContainerAllocator> & v) 
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_FACE_MESSAGE_KEYFRAME_H

