; Auto-generated. Do not edit!


(cl:in-package cordial_core-msg)


;//! \htmlinclude BehaviorFeedback.msg.html

(cl:defclass <BehaviorFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:integer
    :initform 0))
)

(cl:defclass BehaviorFeedback (<BehaviorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BehaviorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BehaviorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cordial_core-msg:<BehaviorFeedback> is deprecated: use cordial_core-msg:BehaviorFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <BehaviorFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_core-msg:status-val is deprecated.  Use cordial_core-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<BehaviorFeedback>)))
    "Constants for message type '<BehaviorFeedback>"
  '((:WAITING . 1)
    (:PLAYING . 2))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'BehaviorFeedback)))
    "Constants for message type 'BehaviorFeedback"
  '((:WAITING . 1)
    (:PLAYING . 2))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BehaviorFeedback>) ostream)
  "Serializes a message object of type '<BehaviorFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'status)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BehaviorFeedback>) istream)
  "Deserializes a message object of type '<BehaviorFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BehaviorFeedback>)))
  "Returns string type for a message object of type '<BehaviorFeedback>"
  "cordial_core/BehaviorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BehaviorFeedback)))
  "Returns string type for a message object of type 'BehaviorFeedback"
  "cordial_core/BehaviorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BehaviorFeedback>)))
  "Returns md5sum for a message object of type '<BehaviorFeedback>"
  "8548bf5d6df4f55a51e5849c9a6d4d5d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BehaviorFeedback)))
  "Returns md5sum for a message object of type 'BehaviorFeedback"
  "8548bf5d6df4f55a51e5849c9a6d4d5d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BehaviorFeedback>)))
  "Returns full string definition for message of type '<BehaviorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%# the name of the behavior we're waiting on~%int32 status~%int32 WAITING = 1~%int32 PLAYING = 2~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BehaviorFeedback)))
  "Returns full string definition for message of type 'BehaviorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%# the name of the behavior we're waiting on~%int32 status~%int32 WAITING = 1~%int32 PLAYING = 2~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BehaviorFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BehaviorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'BehaviorFeedback
    (cl:cons ':status (status msg))
))
