; Auto-generated. Do not edit!


(cl:in-package cordial_core-msg)


;//! \htmlinclude BehaviorResult.msg.html

(cl:defclass <BehaviorResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass BehaviorResult (<BehaviorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BehaviorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BehaviorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cordial_core-msg:<BehaviorResult> is deprecated: use cordial_core-msg:BehaviorResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <BehaviorResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_core-msg:result-val is deprecated.  Use cordial_core-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<BehaviorResult>)))
    "Constants for message type '<BehaviorResult>"
  '((:DONE . 1)
    (:FAILED . 2))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'BehaviorResult)))
    "Constants for message type 'BehaviorResult"
  '((:DONE . 1)
    (:FAILED . 2))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BehaviorResult>) ostream)
  "Serializes a message object of type '<BehaviorResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BehaviorResult>) istream)
  "Deserializes a message object of type '<BehaviorResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BehaviorResult>)))
  "Returns string type for a message object of type '<BehaviorResult>"
  "cordial_core/BehaviorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BehaviorResult)))
  "Returns string type for a message object of type 'BehaviorResult"
  "cordial_core/BehaviorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BehaviorResult>)))
  "Returns md5sum for a message object of type '<BehaviorResult>"
  "d4a5a45c9199e0d95727d00354bde9dd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BehaviorResult)))
  "Returns md5sum for a message object of type 'BehaviorResult"
  "d4a5a45c9199e0d95727d00354bde9dd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BehaviorResult>)))
  "Returns full string definition for message of type '<BehaviorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 result~%int32 DONE = 1~%int32 FAILED = 2~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BehaviorResult)))
  "Returns full string definition for message of type 'BehaviorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 result~%int32 DONE = 1~%int32 FAILED = 2~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BehaviorResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BehaviorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BehaviorResult
    (cl:cons ':result (result msg))
))
