; Auto-generated. Do not edit!


(cl:in-package cordial_core-msg)


;//! \htmlinclude PlayerResult.msg.html

(cl:defclass <PlayerResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass PlayerResult (<PlayerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cordial_core-msg:<PlayerResult> is deprecated: use cordial_core-msg:PlayerResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <PlayerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_core-msg:result-val is deprecated.  Use cordial_core-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<PlayerResult>)))
    "Constants for message type '<PlayerResult>"
  '((:DONE . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'PlayerResult)))
    "Constants for message type 'PlayerResult"
  '((:DONE . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayerResult>) ostream)
  "Serializes a message object of type '<PlayerResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayerResult>) istream)
  "Deserializes a message object of type '<PlayerResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayerResult>)))
  "Returns string type for a message object of type '<PlayerResult>"
  "cordial_core/PlayerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayerResult)))
  "Returns string type for a message object of type 'PlayerResult"
  "cordial_core/PlayerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayerResult>)))
  "Returns md5sum for a message object of type '<PlayerResult>"
  "08a720101bb0c97dedb3c876cd7b3c75")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayerResult)))
  "Returns md5sum for a message object of type 'PlayerResult"
  "08a720101bb0c97dedb3c876cd7b3c75")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayerResult>)))
  "Returns full string definition for message of type '<PlayerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 result~%int32 DONE = 1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayerResult)))
  "Returns full string definition for message of type 'PlayerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 result~%int32 DONE = 1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayerResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayerResult
    (cl:cons ':result (result msg))
))
