; Auto-generated. Do not edit!


(cl:in-package cordial_core-msg)


;//! \htmlinclude PlayerGoal.msg.html

(cl:defclass <PlayerGoal> (roslisp-msg-protocol:ros-message)
  ((phrase
    :reader phrase
    :initarg :phrase
    :type cl:string
    :initform "")
   (interrupt
    :reader interrupt
    :initarg :interrupt
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PlayerGoal (<PlayerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cordial_core-msg:<PlayerGoal> is deprecated: use cordial_core-msg:PlayerGoal instead.")))

(cl:ensure-generic-function 'phrase-val :lambda-list '(m))
(cl:defmethod phrase-val ((m <PlayerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_core-msg:phrase-val is deprecated.  Use cordial_core-msg:phrase instead.")
  (phrase m))

(cl:ensure-generic-function 'interrupt-val :lambda-list '(m))
(cl:defmethod interrupt-val ((m <PlayerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_core-msg:interrupt-val is deprecated.  Use cordial_core-msg:interrupt instead.")
  (interrupt m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayerGoal>) ostream)
  "Serializes a message object of type '<PlayerGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'phrase))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'phrase))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'interrupt) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayerGoal>) istream)
  "Deserializes a message object of type '<PlayerGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'phrase) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'phrase) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:slot-value msg 'interrupt) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayerGoal>)))
  "Returns string type for a message object of type '<PlayerGoal>"
  "cordial_core/PlayerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayerGoal)))
  "Returns string type for a message object of type 'PlayerGoal"
  "cordial_core/PlayerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayerGoal>)))
  "Returns md5sum for a message object of type '<PlayerGoal>"
  "a614444f3a34e4fb06e32a5f1567184a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayerGoal)))
  "Returns md5sum for a message object of type 'PlayerGoal"
  "a614444f3a34e4fb06e32a5f1567184a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayerGoal>)))
  "Returns full string definition for message of type '<PlayerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string phrase~%bool interrupt~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayerGoal)))
  "Returns full string definition for message of type 'PlayerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string phrase~%bool interrupt~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayerGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'phrase))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayerGoal
    (cl:cons ':phrase (phrase msg))
    (cl:cons ':interrupt (interrupt msg))
))
