; Auto-generated. Do not edit!


(cl:in-package cordial_core-msg)


;//! \htmlinclude PlayerFeedback.msg.html

(cl:defclass <PlayerFeedback> (roslisp-msg-protocol:ros-message)
  ((behavior
    :reader behavior
    :initarg :behavior
    :type cl:string
    :initform ""))
)

(cl:defclass PlayerFeedback (<PlayerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cordial_core-msg:<PlayerFeedback> is deprecated: use cordial_core-msg:PlayerFeedback instead.")))

(cl:ensure-generic-function 'behavior-val :lambda-list '(m))
(cl:defmethod behavior-val ((m <PlayerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_core-msg:behavior-val is deprecated.  Use cordial_core-msg:behavior instead.")
  (behavior m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayerFeedback>) ostream)
  "Serializes a message object of type '<PlayerFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'behavior))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'behavior))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayerFeedback>) istream)
  "Deserializes a message object of type '<PlayerFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'behavior) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'behavior) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayerFeedback>)))
  "Returns string type for a message object of type '<PlayerFeedback>"
  "cordial_core/PlayerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayerFeedback)))
  "Returns string type for a message object of type 'PlayerFeedback"
  "cordial_core/PlayerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayerFeedback>)))
  "Returns md5sum for a message object of type '<PlayerFeedback>"
  "03729983c4b9be7a4f2b56846a7ccbdc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayerFeedback)))
  "Returns md5sum for a message object of type 'PlayerFeedback"
  "03729983c4b9be7a4f2b56846a7ccbdc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayerFeedback>)))
  "Returns full string definition for message of type '<PlayerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string behavior~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayerFeedback)))
  "Returns full string definition for message of type 'PlayerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string behavior~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayerFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'behavior))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayerFeedback
    (cl:cons ':behavior (behavior msg))
))
