(cl:defpackage cordial_sprite-msg
  (:use )
  (:export
   "<KEYFRAMEPLAYERGOAL>"
   "KEYFRAMEPLAYERGOAL"
   "<KEYFRAMEPLAYERACTIONRESULT>"
   "KEYFRAMEPLAYERACTIONRESULT"
   "<KEYFRAMEPLAYERACTIONGOAL>"
   "KEYFRAMEPLAYERACTIONGOAL"
   "<KEYFRAMEPLAYERFEEDBACK>"
   "KEYFRAMEPLAYERFEEDBACK"
   "<KEYFRAMEPLAYERACTION>"
   "KEYFRAMEPLAYERACTION"
   "<KEYFRAMEPLAYERACTIONFEEDBACK>"
   "KEYFRAMEPLAYERACTIONFEEDBACK"
   "<KEYFRAMEPLAYERRESULT>"
   "KEYFRAMEPLAYERRESULT"
  ))

