; Auto-generated. Do not edit!


(cl:in-package cordial_sprite-msg)


;//! \htmlinclude KeyframePlayerActionGoal.msg.html

(cl:defclass <KeyframePlayerActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type cordial_sprite-msg:KeyframePlayerGoal
    :initform (cl:make-instance 'cordial_sprite-msg:KeyframePlayerGoal)))
)

(cl:defclass KeyframePlayerActionGoal (<KeyframePlayerActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <KeyframePlayerActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'KeyframePlayerActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cordial_sprite-msg:<KeyframePlayerActionGoal> is deprecated: use cordial_sprite-msg:KeyframePlayerActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <KeyframePlayerActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_sprite-msg:header-val is deprecated.  Use cordial_sprite-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <KeyframePlayerActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_sprite-msg:goal_id-val is deprecated.  Use cordial_sprite-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <KeyframePlayerActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cordial_sprite-msg:goal-val is deprecated.  Use cordial_sprite-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <KeyframePlayerActionGoal>) ostream)
  "Serializes a message object of type '<KeyframePlayerActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <KeyframePlayerActionGoal>) istream)
  "Deserializes a message object of type '<KeyframePlayerActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<KeyframePlayerActionGoal>)))
  "Returns string type for a message object of type '<KeyframePlayerActionGoal>"
  "cordial_sprite/KeyframePlayerActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'KeyframePlayerActionGoal)))
  "Returns string type for a message object of type 'KeyframePlayerActionGoal"
  "cordial_sprite/KeyframePlayerActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<KeyframePlayerActionGoal>)))
  "Returns md5sum for a message object of type '<KeyframePlayerActionGoal>"
  "a440f48ebd54cf53b44b336f2315e19e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'KeyframePlayerActionGoal)))
  "Returns md5sum for a message object of type 'KeyframePlayerActionGoal"
  "a440f48ebd54cf53b44b336f2315e19e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<KeyframePlayerActionGoal>)))
  "Returns full string definition for message of type '<KeyframePlayerActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%KeyframePlayerGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cordial_sprite/KeyframePlayerGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string behavior~%string[] args~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'KeyframePlayerActionGoal)))
  "Returns full string definition for message of type 'KeyframePlayerActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%KeyframePlayerGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cordial_sprite/KeyframePlayerGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string behavior~%string[] args~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <KeyframePlayerActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <KeyframePlayerActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'KeyframePlayerActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
