(cl:in-package cordial_tablet-msg)
(cl:export '(ID-VAL
          ID
          NAME-VAL
          NAME
          ACTION-VAL
          ACTION
          IMG_LOC-VAL
          IMG_LOC
          TYPE-VAL
          TYPE
          TEXT-VAL
          TEXT
          TEXTSIZE-VAL
          TEXTSIZE
          X-VAL
          X
          Y-VAL
          Y
          TINT-VAL
          TINT
          FILLED-VAL
          FILLED
          BCOLOR-VAL
          BCOLOR
          ANGLE-VAL
          ANGLE
          SCALEX-VAL
          SCALEX
          SCALEY-VAL
          SCALEY
))