(cl:defpackage cordial_tablet-msg
  (:use )
  (:export
   "<TOKENLOCATION>"
   "TOKENLOCATION"
   "<TOKENPOSES>"
   "TOKENPOSES"
   "<CHANGETOKEN>"
   "CHANGETOKEN"
   "<TABLETSTATUS>"
   "TABLETSTATUS"
   "<RELOAD>"
   "RELOAD"
   "<TOKENPOSE>"
   "TOKENPOSE"
   "<ADDREMOVEAREA>"
   "ADDREMOVEAREA"
   "<TOKENLOCATIONS>"
   "TOKENLOCATIONS"
   "<DISPBANNER>"
   "DISPBANNER"
  ))

