(cl:in-package cordial_tablet-msg)
(cl:export '(ID-VAL
          ID
          NAME-VAL
          NAME
          TEXT-VAL
          TEXT
          X-VAL
          X
          Y-VAL
          Y
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          DRAWN-VAL
          DRAWN
          FILLED-VAL
          FILLED
          BCOLOR-VAL
          BCOLOR
          ARRANGE-VAL
          ARRANGE
          IMG-VAL
          IMG
          TEXTX-VAL
          TEXTX
          TEXTY-VAL
          TEXTY
          TEXTSIZE-VAL
          TEXTSIZE
          XPADDING-VAL
          XPADDING
          YPADDING-VAL
          YPADDING
))