/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_tablet/msg/DispBanner.msg */
#ifndef CORDIAL_TABLET_MESSAGE_DISPBANNER_H
#define CORDIAL_TABLET_MESSAGE_DISPBANNER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cordial_tablet
{
template <class ContainerAllocator>
struct DispBanner_ {
  typedef DispBanner_<ContainerAllocator> Type;

  DispBanner_()
  : s()
  , action()
  {
  }

  DispBanner_(const ContainerAllocator& _alloc)
  : s(_alloc)
  , action(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _s_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  s;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  action;


  typedef boost::shared_ptr< ::cordial_tablet::DispBanner_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_tablet::DispBanner_<ContainerAllocator>  const> ConstPtr;
}; // struct DispBanner
typedef  ::cordial_tablet::DispBanner_<std::allocator<void> > DispBanner;

typedef boost::shared_ptr< ::cordial_tablet::DispBanner> DispBannerPtr;
typedef boost::shared_ptr< ::cordial_tablet::DispBanner const> DispBannerConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_tablet::DispBanner_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_tablet::DispBanner_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_tablet

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_tablet::DispBanner_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_tablet::DispBanner_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_tablet::DispBanner_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e9a2ee18d894534f8508fce210184419";
  }

  static const char* value(const  ::cordial_tablet::DispBanner_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe9a2ee18d894534fULL;
  static const uint64_t static_value2 = 0x8508fce210184419ULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_tablet::DispBanner_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_tablet/DispBanner";
  }

  static const char* value(const  ::cordial_tablet::DispBanner_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_tablet::DispBanner_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string s\n\
string action\n\
\n\
";
  }

  static const char* value(const  ::cordial_tablet::DispBanner_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_tablet::DispBanner_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s);
    stream.next(m.action);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct DispBanner_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_tablet::DispBanner_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_tablet::DispBanner_<ContainerAllocator> & v) 
  {
    s << indent << "s: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.s);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_TABLET_MESSAGE_DISPBANNER_H

