/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_tablet/msg/Reload.msg */
#ifndef CORDIAL_TABLET_MESSAGE_RELOAD_H
#define CORDIAL_TABLET_MESSAGE_RELOAD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cordial_tablet
{
template <class ContainerAllocator>
struct Reload_ {
  typedef Reload_<ContainerAllocator> Type;

  Reload_()
  : s()
  {
  }

  Reload_(const ContainerAllocator& _alloc)
  : s(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _s_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  s;


  typedef boost::shared_ptr< ::cordial_tablet::Reload_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_tablet::Reload_<ContainerAllocator>  const> ConstPtr;
}; // struct Reload
typedef  ::cordial_tablet::Reload_<std::allocator<void> > Reload;

typedef boost::shared_ptr< ::cordial_tablet::Reload> ReloadPtr;
typedef boost::shared_ptr< ::cordial_tablet::Reload const> ReloadConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_tablet::Reload_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_tablet::Reload_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_tablet

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_tablet::Reload_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_tablet::Reload_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_tablet::Reload_<ContainerAllocator> > {
  static const char* value() 
  {
    return "81af3411577d82a6786258523fc891ce";
  }

  static const char* value(const  ::cordial_tablet::Reload_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x81af3411577d82a6ULL;
  static const uint64_t static_value2 = 0x786258523fc891ceULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_tablet::Reload_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_tablet/Reload";
  }

  static const char* value(const  ::cordial_tablet::Reload_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_tablet::Reload_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string s\n\
\n\
";
  }

  static const char* value(const  ::cordial_tablet::Reload_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_tablet::Reload_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Reload_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_tablet::Reload_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_tablet::Reload_<ContainerAllocator> & v) 
  {
    s << indent << "s: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.s);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_TABLET_MESSAGE_RELOAD_H

