/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_tablet/msg/TokenLocations.msg */
#ifndef CORDIAL_TABLET_MESSAGE_TOKENLOCATIONS_H
#define CORDIAL_TABLET_MESSAGE_TOKENLOCATIONS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "cordial_tablet/TokenLocation.h"

namespace cordial_tablet
{
template <class ContainerAllocator>
struct TokenLocations_ {
  typedef TokenLocations_<ContainerAllocator> Type;

  TokenLocations_()
  : id()
  , locations()
  {
  }

  TokenLocations_(const ContainerAllocator& _alloc)
  : id(_alloc)
  , locations(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  id;

  typedef std::vector< ::cordial_tablet::TokenLocation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cordial_tablet::TokenLocation_<ContainerAllocator> >::other >  _locations_type;
  std::vector< ::cordial_tablet::TokenLocation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cordial_tablet::TokenLocation_<ContainerAllocator> >::other >  locations;


  typedef boost::shared_ptr< ::cordial_tablet::TokenLocations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_tablet::TokenLocations_<ContainerAllocator>  const> ConstPtr;
}; // struct TokenLocations
typedef  ::cordial_tablet::TokenLocations_<std::allocator<void> > TokenLocations;

typedef boost::shared_ptr< ::cordial_tablet::TokenLocations> TokenLocationsPtr;
typedef boost::shared_ptr< ::cordial_tablet::TokenLocations const> TokenLocationsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_tablet::TokenLocations_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_tablet::TokenLocations_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_tablet

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_tablet::TokenLocations_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_tablet::TokenLocations_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_tablet::TokenLocations_<ContainerAllocator> > {
  static const char* value() 
  {
    return "75fff0208301d539b57e1de8f7c3e40e";
  }

  static const char* value(const  ::cordial_tablet::TokenLocations_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x75fff0208301d539ULL;
  static const uint64_t static_value2 = 0xb57e1de8f7c3e40eULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_tablet::TokenLocations_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_tablet/TokenLocations";
  }

  static const char* value(const  ::cordial_tablet::TokenLocations_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_tablet::TokenLocations_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string id\n\
cordial_tablet/TokenLocation[] locations\n\
================================================================================\n\
MSG: cordial_tablet/TokenLocation\n\
string instanceid\n\
string tokenid\n\
float64 x\n\
float64 y\n\
string[] areas\n\
";
  }

  static const char* value(const  ::cordial_tablet::TokenLocations_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_tablet::TokenLocations_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.locations);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct TokenLocations_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_tablet::TokenLocations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_tablet::TokenLocations_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "locations[]" << std::endl;
    for (size_t i = 0; i < v.locations.size(); ++i)
    {
      s << indent << "  locations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cordial_tablet::TokenLocation_<ContainerAllocator> >::stream(s, indent + "    ", v.locations[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_TABLET_MESSAGE_TOKENLOCATIONS_H

