/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_core/msg/BehaviorResult.msg */
#ifndef CORDIAL_CORE_MESSAGE_BEHAVIORRESULT_H
#define CORDIAL_CORE_MESSAGE_BEHAVIORRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cordial_core
{
template <class ContainerAllocator>
struct BehaviorResult_ {
  typedef BehaviorResult_<ContainerAllocator> Type;

  BehaviorResult_()
  : result(0)
  {
  }

  BehaviorResult_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;

  enum { DONE = 1 };
  enum { FAILED = 2 };

  typedef boost::shared_ptr< ::cordial_core::BehaviorResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_core::BehaviorResult_<ContainerAllocator>  const> ConstPtr;
}; // struct BehaviorResult
typedef  ::cordial_core::BehaviorResult_<std::allocator<void> > BehaviorResult;

typedef boost::shared_ptr< ::cordial_core::BehaviorResult> BehaviorResultPtr;
typedef boost::shared_ptr< ::cordial_core::BehaviorResult const> BehaviorResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_core::BehaviorResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_core::BehaviorResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_core::BehaviorResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_core::BehaviorResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_core::BehaviorResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d4a5a45c9199e0d95727d00354bde9dd";
  }

  static const char* value(const  ::cordial_core::BehaviorResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd4a5a45c9199e0d9ULL;
  static const uint64_t static_value2 = 0x5727d00354bde9ddULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_core::BehaviorResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_core/BehaviorResult";
  }

  static const char* value(const  ::cordial_core::BehaviorResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_core::BehaviorResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 result\n\
int32 DONE = 1\n\
int32 FAILED = 2\n\
\n\
";
  }

  static const char* value(const  ::cordial_core::BehaviorResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::cordial_core::BehaviorResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_core::BehaviorResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct BehaviorResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_core::BehaviorResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_core::BehaviorResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_CORE_MESSAGE_BEHAVIORRESULT_H

