/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_core/msg/BehaviorActionGoal.msg */
#ifndef CORDIAL_CORE_MESSAGE_BEHAVIORACTIONGOAL_H
#define CORDIAL_CORE_MESSAGE_BEHAVIORACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "cordial_core/BehaviorGoal.h"

namespace cordial_core
{
template <class ContainerAllocator>
struct BehaviorActionGoal_ {
  typedef BehaviorActionGoal_<ContainerAllocator> Type;

  BehaviorActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  BehaviorActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::cordial_core::BehaviorGoal_<ContainerAllocator>  _goal_type;
   ::cordial_core::BehaviorGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_core::BehaviorActionGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct BehaviorActionGoal
typedef  ::cordial_core::BehaviorActionGoal_<std::allocator<void> > BehaviorActionGoal;

typedef boost::shared_ptr< ::cordial_core::BehaviorActionGoal> BehaviorActionGoalPtr;
typedef boost::shared_ptr< ::cordial_core::BehaviorActionGoal const> BehaviorActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_core::BehaviorActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_core::BehaviorActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f6b86703a7f09d804377f9d528e0bbe1";
  }

  static const char* value(const  ::cordial_core::BehaviorActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf6b86703a7f09d80ULL;
  static const uint64_t static_value2 = 0x4377f9d528e0bbe1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_core/BehaviorActionGoal";
  }

  static const char* value(const  ::cordial_core::BehaviorActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
BehaviorGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: cordial_core/BehaviorGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
# name of the behavior\n\
string behavior\n\
\n\
# at what time should we be finished moving/holding\n\
# holding only meaningful if blocking or return to prior is true\n\
time end_move\n\
time end_hold\n\
\n\
# return to previous pose when behavior is done?\n\
bool return_to_prior\n\
\n\
# if the relevant DOFs are in conflict, what to do?\n\
# Queue: play behavior once DOFs are free; end_move and end_hold are taken to be relative to time.now\n\
# Drop: never play the behavior\n\
# Override: cancel the current behavior and play the new one\n\
int32 if_conflict\n\
int32 QUEUE = 0\n\
int32 DROP = 1\n\
int32 OVERRIDE = 2\n\
\n\
# some behaviors may take arguments, e.g., a frame for lookat\n\
string[] args\n\
\n\
# have robot controller block on this\n\
# if true, then wait_for_result will block until the behavior is done\n\
bool wait_and_block\n\
\n\
";
  }

  static const char* value(const  ::cordial_core::BehaviorActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cordial_core::BehaviorActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct BehaviorActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_core::BehaviorActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_core::BehaviorActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::cordial_core::BehaviorGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_CORE_MESSAGE_BEHAVIORACTIONGOAL_H

