/* Auto-generated by genmsg_cpp for file /home/michellebecerra/kinetic_ws/sandbox/cordial-public/cordial_core/msg/PlayerResult.msg */
#ifndef CORDIAL_CORE_MESSAGE_PLAYERRESULT_H
#define CORDIAL_CORE_MESSAGE_PLAYERRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cordial_core
{
template <class ContainerAllocator>
struct PlayerResult_ {
  typedef PlayerResult_<ContainerAllocator> Type;

  PlayerResult_()
  : result(0)
  {
  }

  PlayerResult_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;

  enum { DONE = 1 };

  typedef boost::shared_ptr< ::cordial_core::PlayerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cordial_core::PlayerResult_<ContainerAllocator>  const> ConstPtr;
}; // struct PlayerResult
typedef  ::cordial_core::PlayerResult_<std::allocator<void> > PlayerResult;

typedef boost::shared_ptr< ::cordial_core::PlayerResult> PlayerResultPtr;
typedef boost::shared_ptr< ::cordial_core::PlayerResult const> PlayerResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cordial_core::PlayerResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cordial_core::PlayerResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cordial_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cordial_core::PlayerResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cordial_core::PlayerResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cordial_core::PlayerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "08a720101bb0c97dedb3c876cd7b3c75";
  }

  static const char* value(const  ::cordial_core::PlayerResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x08a720101bb0c97dULL;
  static const uint64_t static_value2 = 0xedb3c876cd7b3c75ULL;
};

template<class ContainerAllocator>
struct DataType< ::cordial_core::PlayerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cordial_core/PlayerResult";
  }

  static const char* value(const  ::cordial_core::PlayerResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cordial_core::PlayerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 result\n\
int32 DONE = 1\n\
\n\
";
  }

  static const char* value(const  ::cordial_core::PlayerResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::cordial_core::PlayerResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cordial_core::PlayerResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct PlayerResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cordial_core::PlayerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cordial_core::PlayerResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORDIAL_CORE_MESSAGE_PLAYERRESULT_H

